property_version=3.00
band.23.pa_calibration=53.000000
band.22.pa_calibration=53.000000
band.21.pa_calibration=53.000000
band.20.pa_calibration=53.000000
band.19.pa_calibration=53.000000
band.18.pa_calibration=53.000000
band.17.pa_calibration=53.000000
band.16.pa_calibration=53.000000
band.15.pa_calibration=53.000000
band.14.pa_calibration=53.000000
band.13.pa_calibration=38.800000
band.12.pa_calibration=41.100000
band.11.pa_calibration=42.800000
band.10.pa_calibration=41.300000
band.9.pa_calibration=46.000000
band.8.pa_calibration=46.600000
band.7.pa_calibration=47.100000
band.6.pa_calibration=47.000000
band.5.pa_calibration=46.900000
band.4.pa_calibration=45.400000
band.3.pa_calibration=46.000000
band.2.pa_calibration=44.300000
band.1.pa_calibration=38.800000
band.0.pa_calibration=38.800000
device_id=1001
