/* Copyright (C)
* 2017 - John Melton, G0ORX/N6LYT
* 2024-2026 - Heiko Amft, DL1BZ (Project deskHPSDR)
*
* SPDX-License-Identifier: GPL-3.0-or-later
*
*   This program is free software: you can redistribute it and/or modify
*   it under the terms of the GNU General Public License as published by
*   the Free Software Foundation, either version 3 of the License, or
*   (at your option) any later version.
*
*   This program is distributed in the hope that it will be useful,
*   but WITHOUT ANY WARRANTY; without even the implied warranty of
*   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*   GNU General Public License for more details.
*
*   You should have received a copy of the GNU General Public License
*   along with this program.  If not, see <https://www.gnu.org/licenses/>.
*
*/

#include <gtk/gtk.h>
#include <errno.h>
#include <string.h>
#include "css.h"
#include "ddc_menu.h"
#include "discovery.h"
#include "message.h"
#include "screen_menu.h"
#include "main.h"
#include "toolset.h"
#include "property.h"
#include "protocols.h"

const char *css_filename = "deskhpsdr.css";

//////////////////////////////////////////////////////////////////////////////////////////
//
// Normally one wants to inherit everything from the GTK theme.
// In some cases, however, this does not work too well. But the
// principle here is to change as little as possible.
//
// Here is a list of CSS definitions we make here:
//
// boldlabel           This is used to write texts in menus and the slider area,
//                     therefore it contains 3px border
//
// slider1             Used for slider and zoompan areas for small  screen width
// slider2             Used for slider and zoompan areas for medium screen width
// slider3             Used for slider and zoompan areas for large  screen width
//
// big_txt             This is a large bold text. Used for the "pi label" on the
//                     discovery screen, and the "Start" button there
//
// med_txt             This is a large text. Used for the status bar, etc.
//
// small_txt           This is a small text, used where space is scarce.
//
// close_button        Style for the "Close" button in the menus, so it can be
//                     easily recognized
//
// small_button        15px text with minimal paddding. Used in menus where one wants
//                     to make the buttons narrow.
//
// medium_button       the same as small_button but with 20px
//
// large_button        the same as small_button but with 25px
//
// small_toggle_button Used for the buttons in action dialogs, and the filter etc.
//                     menus where the current choice needs proper high-lighting
//
// popup_scale         Used to define the slider that "pops up" when e.g. AF volume
//                     is changed via GPIO/MIDI but no sliders are on display
//
// checkbutton         THe standard button is Very difficult to see on RaspPi with
//                     a light GTK theme. So we use our own, and draw a grey border
//                     so this should be OK for both the light and dark theme.
//
// radiobutton         see checkbutton.
//
//////////////////////////////////////////////////////////////////////////////////////////
//
// Note on font sizes:
//
// A RaspPi has different default settings whether you have a small screen, a medium
// screen or a large screen (RaspBerry Menu ==> Preferences ==> Appearances Settings).
//
// For a fixed size such as the height of the Sliders or Zoompan area, we therefore
// MUST specify the font size. If not, it may happen that the sliders cannot be
// displayed on a large screen
//
//////////////////////////////////////////////////////////////////////////////////////////
char *css =
        "  * { font-family:'JetBrains Mono', Tahoma, Sans; }\n"
        "  combobox { font-size: 15px; }\n"
        "  button   { font-size: 15px; background-image: none; border-width: 2px; }\n"
        "  button:hover {\n"
        "    background-image: none;\n"
        "    box-shadow: inset 0 0 0 9999px rgba(0,0,0,0.06);\n"
        "  }\n"
        "  scrolledwindow viewport button:hover {\n"
        "    background-image: none;\n"
        "    border-width: 3px;\n"
        "  }\n"
        "  checkbutton label { font-size: 15px; }\n"
        "  spinbutton { font-size: 15px; }\n"
        "  radiobutton label  { font-size: 15px; }\n"
        "  scale { font-size: 15px; }\n"
        "  entry { font-size: 15px; }\n"
        "  textview.dxcluster-textview-linux {\n"
        "    font-family: 'JetBrains Mono', Tahoma, Sans;\n"
        "    font-size: 12pt;\n"
        "  }\n"
        "  entry.dxcluster-entry-linux {\n"
        "    font-family: 'JetBrains Mono', Tahoma, Sans;\n"
        "    font-size: 12pt;\n"
        "  }\n"
        "  textview.dxcluster-textview {\n"
        "    font-family: 'JetBrains Mono', Tahoma, Sans;\n"
        "    font-size: 14pt;\n"
        "  }\n"
        "  entry.dxcluster-entry {\n"
        "    font-family: 'JetBrains Mono', Tahoma, Sans;\n"
        "    font-size: 14pt;\n"
        "  }\n"
        "  notebook { font-size: 15px; }\n"
        "  tooltip, GtkWindow.tooltip {\n"
        "    text-shadow: none;\n"
        "    opacity: 1.0;\n"
        "    background-color: #ffffcc;\n"
        "    background-image: none;\n"
        "    color: #000000;\n"
        "  }\n"
        "  tooltip label, GtkWindow.tooltip label {\n"
        "    color: #000000;\n"
        "    opacity: 1.0;\n"
        "    text-shadow: none;\n"
        "    font-family: 'JetBrains Mono', Tahoma, Sans;\n"
        "    font-size: 13px;\n"
        "  }\n"
        "  #boldlabel {\n"
        "    padding: 3px;\n"
        "    font-family: 'JetBrains Mono', Tahoma, Sans;\n"
        "    font-weight: bold;\n"
        "    font-size: 15px;\n"
        "  }\n"
        "  #boldlabel_vfo_sf {\n"
        "    padding: 3px;\n"
        "    border: 1px solid darkblue;\n"
        "    border-radius: 6px;\n"
        "    background-image: none;\n"
        "    font-family: 'JetBrains Mono', Tahoma, Sans;\n"
        "    font-weight: bold;\n"
        "    font-size: 15px;\n"
        "    color: darkblue;\n"
        "  }\n"
        "  #boldlabel_vfo_sf:hover {\n"
        "    background-color: rgb(0%, 100%, 0%);\n"    // background if selected
        "    background-image: none;\n"
        "  }\n"
        "  #boldlabel_red {\n"
        "    padding: 3px;\n"
        "    font-family: 'JetBrains Mono', Tahoma, Sans;\n"
        "    font-weight: bold;\n"
        "    font-size: 15px;\n"
        "    color: red;\n"
        "  }\n"
        "  #boldlabel_blue {\n"
        "    padding: 3px;\n"
        "    font-family: 'JetBrains Mono', Tahoma, Sans;\n"
        "    font-weight: bold;\n"
        "    font-size: 15px;\n"
        "    color: darkblue;\n"
        "  }\n"
        "  #boldlabel_border_blue {\n"
        "    padding: 3px;\n"
        "    border: 1px solid darkblue;\n"
        "    border-radius: 6px;\n"
        "    font-family: 'JetBrains Mono', Tahoma, Sans;\n"
        "    font-weight: bold;\n"
        "    font-size: 16px;\n"
        "    color: darkblue;\n"
        "  }\n"
        "  #boldlabel_border_black {\n"
        "    padding: 3px;\n"
        "    border: 2px solid black;\n"
        "    border-radius: 6px;\n"
        "    font-family: 'JetBrains Mono', Tahoma, Sans;\n"
        "    font-weight: bold;\n"
        "    font-size: 16px;\n"
        "    color: black;\n"
        "  }\n"
        "  #stdlabel {\n"
        "    padding: 3px;\n"
        "    font-family: 'JetBrains Mono', Tahoma, Sans;\n"
        "    font-weight: normal;\n"
        "    font-size: 15px;\n"
        "  }\n"
        "  #stdlabel_blue {\n"
        "    padding: 3px;\n"
        "    font-family: 'JetBrains Mono', Tahoma, Sans;\n"
        "    font-weight: normal;\n"
        "    font-size: 15px;\n"
        "    color: darkblue;\n"
        "  }\n"
        "  #smalllabel {\n"
        "    padding: 3px;\n"
        "    font-family: 'JetBrains Mono', Tahoma, Sans;\n"
        "    font-weight: normal;\n"
        "    font-size: 13px;\n"
        "  }\n"
        "  #smalllabel_bold {\n"
        "    font-family: 'JetBrains Mono', Tahoma, Sans;\n"
        "    font-weight: bold;\n"
        "    font-size: 13px;\n"
        "  }\n"
        "  #smalllabel_red {\n"
        "    font-family: 'JetBrains Mono', Tahoma, Sans;\n"
        "    font-weight: normal;\n"
        "    font-size: 13px;\n"
        "    color: red\n"
        "  }\n"
        "  #smalllabel_red_bold {\n"
        "    font-family: 'JetBrains Mono', Tahoma, Sans;\n"
        "    font-weight: bold;\n"
        "    font-size: 13px;\n"
        "    color: red\n"
        "  }\n"
        "  #smalllabel_blue_bold {\n"
        "    font-family: 'JetBrains Mono', Tahoma, Sans;\n"
        "    font-weight: bold;\n"
        "    font-size: 13px;\n"
        "    color: darkblue\n"
        "  }\n"
        "  #slider0   {\n"
        "    padding: 3px;\n"
        "    font-family: 'JetBrains Mono', Tahoma, Sans;\n"
        "    font-weight: bold;\n"
        "    font-size: 14px;\n"
        "  }\n"
        "  #slider1   {\n"
        "    padding: 3px;\n"
        "    font-family: 'JetBrains Mono', Tahoma, Sans;\n"
        "    font-weight: bold;\n"
        "    font-size: 16px;\n"
        "  }\n"
        "  #slider2   {\n"
        "    padding: 3px;\n"
        "    font-family: 'JetBrains Mono', Tahoma, Sans;\n"
        "    font-weight: normal;\n"
        "    font-size: 16px;\n"
        "  }\n"
        "  #slider2_blue {\n"
        "    padding: 3px;\n"
        "    font-family: 'JetBrains Mono', Tahoma, Sans;\n"
        "    font-weight: normal;\n"
        "    font-size: 16px;\n"
        "    color: darkblue;\n"
        "  }\n"
        "  #slider2_red {\n"
        "    padding: 3px;\n"
        "    font-family: 'JetBrains Mono', Tahoma, Sans;\n"
        "    font-weight: normal;\n"
        "    font-size: 16px;\n"
        "    color: red;\n"
        "  }\n"
        "  #label2_grey {\n"
        "    padding: 3px;\n"
        "    font-family: 'JetBrains Mono', Tahoma, Sans;\n"
        "    font-weight: normal;\n"
        "    font-size: 18px;\n"
        "    color: #c2c2c2;\n"
        "  }\n"
        "  #slider3   {\n"
        "    padding: 3px;\n"
        "    font-family: 'JetBrains Mono', Tahoma, Sans;\n"
        "    font-weight: normal;\n"
        "    font-size: 22px;\n"
        "  }\n"
        "  #big_txt {\n"
        "    font-family: Tahoma, Sans;\n"
        "    font-size: 22px;\n"
        "    font-weight: bold;\n"
        "    }\n"
        "  #med_txt {\n"
        "    font-family: Tahoma, Sans;\n"
        "    font-size: 18px;\n"
        "    }\n"
        "  #med_bold_txt {\n"
        "    font-family: Tahoma, Sans;\n"
        "    font-size: 18px;\n"
        "    font-weight: bold;\n"
        "    }\n"
        "  #small_txt {\n"
        "    font-family: Tahoma, Sans;\n"
        "    font-weight: bold;\n"
        "    font-size: 12px;\n"
        "    }\n"
        "  #small_bold_txt {\n"
        "    font-family: Tahoma, Sans;\n"
        "    font-weight: bold;\n"
        "    font-size: 16px;\n"
        "    }\n"
        "  #small_bold_txt_blue {\n"
        "    font-family: Tahoma, Sans;\n"
        "    font-weight: bold;\n"
        "    font-size: 16px;\n"
        "    color: darkblue;\n"
        "    }\n"
        "  #discovery_btn {\n"
        "    padding: 3px;\n"
        "    border: 1px solid darkblue;\n"
        "    border-radius: 6px;\n"
        "    font-family: 'JetBrains Mono', Tahoma, Sans;\n"
        "    font-size: 18px;\n"
        "    font-weight: bold;\n"
        "    background-image: none;\n"
        "    color: darkblue;\n"
        "    }\n"
        "  #discovery_btn:hover {\n"
        "    background-color: rgb(0%, 100%, 0%);\n"    // background if selected
        "    background-image: none;\n"
        "    }\n"
        "  #close_button {\n"
        "    padding: 5px;\n"
        "    font-family: 'JetBrains Mono', Tahoma, Sans;\n"
        "    font-size: 15px;\n"
        "    font-weight: bold;\n"
        "    border: 1px solid rgb(50%, 50%, 50%);\n"
        "    background-image: none;\n"
        "    }\n"
        "  #close_button:hover {\n"
        "    background-color: rgb(0%, 100%, 0%);\n"    // background if selected
        "    background-image: none;\n"
        "    }\n"
        "  #small_button {\n"
        "    padding: 1px;\n"
        "    border: 1px solid darkblue;\n"
        "    border-radius: 6px;\n"
        "    font-family: 'JetBrains Mono', Tahoma, Sans;\n"
        "    font-size: 15px;\n"
        "    font-weight: bold;\n"
        "    color: darkblue;\n"
        "    background-image: none;\n"
        "    }\n"
        "  #medium_button {\n"
        "    padding: 1px;\n"
        "    border: 1px solid darkblue;\n"
        "    border-radius: 6px;\n"
        "    font-family: 'JetBrains Mono', Tahoma, Sans;\n"
        "    font-size: 20px;\n"
        "    font-weight: bold;\n"
        "    color: darkblue;\n"
        "    background-image: none;\n"
        "    }\n"
        "  #medium_button:hover {\n"
        "    background-color: rgb(0%, 100%, 0%);\n"    // background if selected
        "    background-image: none;\n"
        "    }\n"
        "  #large_button {\n"
        "    padding: 1px;\n"
        "    border: 1px solid darkblue;\n"
        "    border-radius: 6px;\n"
        "    font-family: 'JetBrains Mono', Tahoma, Sans;\n"
        "    font-size: 25px;\n"
        "    font-weight: bold;\n"
        "    color: darkblue;\n"
        "    background-image: none;\n"
        "    }\n"
        "  #small_button_with_border {\n"
        "    padding: 3px;\n"
        "    font-family: 'JetBrains Mono', Tahoma, Sans;\n"
        "    font-size: 15px;\n"
        "    border: 1px solid rgb(50%, 50%, 50%);\n"
        "    }\n"
        "  #small_toggle_button {\n"
        "    padding: 1px;\n"
        "    border: 1px solid darkblue;\n"
        "    font-family: 'JetBrains Mono', Tahoma, Sans;\n"
        "    font-size: 15px;\n"
        "    font-weight: bold;\n"
        "    background-image: none;\n"
        "    color: darkblue;\n"
        "    }\n"
        "  #small_toggle_button:checked {\n"
        "    padding: 1px;\n"
        "    border: 1px solid darkblue;\n"
        "    font-family: 'JetBrains Mono', Tahoma, Sans;\n"
        "    font-size: 15px;\n"
        "    font-weight: bold;\n"
        "    background-image: none;\n"
        "    background-color: rgb(0%, 100%, 0%);\n"    // background if selected
        "    color: rgb(0%, 0%, 0%);\n"               // text if selected
        "    }\n"
        "  #medium_toggle_button {\n"
        "    padding: 1px;\n"
        "    border: 1px solid darkblue;\n"
        "    border-radius: 6px;\n"
        "    font-family: 'JetBrains Mono', Tahoma, Sans;\n"
        "    font-size: 13px;\n"
        "    font-weight: bold;\n"
        "    background-image: none;\n"
        "    color: darkblue;\n"
        "    }\n"
        "  #medium_toggle_button.active {\n"
        "    padding: 1px;\n"
        "    border: 1px solid darkblue;\n"
        "    border-radius: 6px;\n"
        "    font-family: 'JetBrains Mono', Tahoma, Sans;\n"
        "    font-size: 13px;\n"
        "    font-weight: bold;\n"
        "    background-image: none;\n"
        "    background-color: rgb(0%, 100%, 0%);\n"    // background if selected
        "    color: darkblue;\n"                        // text if selected
        "    }\n"
        "  #medium_toggle_button:checked {\n"
        "    padding: 1px;\n"
        "    border: 1px solid darkblue;\n"
        "    border-radius: 6px;\n"
        "    font-family: 'JetBrains Mono', Tahoma, Sans;\n"
        "    font-size: 13px;\n"
        "    font-weight: bold;\n"
        "    background-image: none;\n"
        "    background-color: rgb(0%, 100%, 0%);\n"    // background if selected
        "    color: darkblue;\n"                        // text if selected
        "    }\n"
        "  #medium_toggle_button:active {\n"
        "    padding: 1px;\n"
        "    border: 1px solid darkblue;\n"
        "    border-radius: 6px;\n"
        "    font-family: 'JetBrains Mono', Tahoma, Sans;\n"
        "    font-size: 13px;\n"
        "    font-weight: bold;\n"
        "    background-image: none;\n"
        "    background-color: rgb(0%, 100%, 0%);\n"    // background if selected
        "    color: darkblue;\n"                        // text if selected
        "    }\n"
        "  #front_toggle_button {\n"
        "    padding: 1px;\n"
        "    border: 1px solid darkblue;\n"
        "    border-radius: 6px;\n"
        "    font-family: 'JetBrains Mono', Tahoma, Sans;\n"
        "    font-size: 13px;\n"
        "    font-weight: bold;\n"
        "    background-image: none;\n"
        "    background-color: rgb(100%, 20%, 20%);\n"    // background if selected
        "    color: rgb(100%, 100%, 100%);\n"             // text if selected
        "    }\n"
        "  #front_toggle_button:checked {\n"
        "    padding: 1px;\n"
        "    border: 1px solid darkblue;\n"
        "    border-radius: 6px;\n"
        "    font-family: 'JetBrains Mono', Tahoma, Sans;\n"
        "    font-size: 13px;\n"
        "    font-weight: bold;\n"
        "    background-image: none;\n"
        "    background-color: rgb(0%, 100%, 0%);\n"    // background if selected
        "    color: rgb(0%, 0%, 0%);\n"                 // text if selected
        "    }\n"
        "  #front_toggle_button:disabled {\n"
        "    padding: 1px;\n"
        "    border: 1px solid darkgrey;\n"
        "    border-radius: 6px;\n"
        "    background-color: #ccc;\n"                 // grauer Hintergrund
        "    color: #888;\n"                            // grauer Text
        "    }\n"
        "  #front_toggle_button:checked:disabled {\n"
        "    padding: 1px;\n"
        "    border: 1px solid darkgrey;\n"
        "    border-radius: 6px;\n"
        "    background-color: #ccc;\n"                 // grauer Hintergrund
        "    color: #888;\n"                            // grauer Text
        "    }\n"
        "  #popup_scale slider {\n"
        "    background: rgb(  0%,  0%, 100%);\n"         // Slider handle
        "    }\n"
        "  #popup_scale trough {\n"
        "    background: rgb( 50%, 50%, 100%);\n"         // Slider bar
        "    }\n"
        "  #popup_scale value {\n"
        "    color: rgb(100%, 10%, 10%);\n"              // digits
        "    font-size: 15px;\n"
        "    }\n"
        "  checkbutton:checked > check {\n"
        "    border: 1px solid rgb(50%, 50%, 50%);\n"
        "    background-color: darkgreen;\n"  // Hintergrundfarbe des CheckButtons selbst
        "    border-color: darkgreen;\n"
        "    background-image: none;\n"
        "    }\n"
        "  radiobutton radio {\n"
        "    border: 1px solid rgb(50%, 50%, 50%);\n"
        "    }\n"
        "  headerbar {\n"
        "    min-height: 0px;\n"
        "    padding: 0px;\n"
        "    margin: 0px;\n"
        "    font-size: 15px;\n"
        "    font-family: Tahoma, Sans;\n"
        "    }\n"
        "  scale value {\n"
        "    color: darkblue;\n"
        "    font-weight: bold;\n"
        "    }\n"
        "  scale marks {\n"
        "    color: darkblue;\n"
        "    }\n"
        "  scale mark {\n"
        "    color: darkblue;\n"
        "    }\n"
        "  scale slider {\n"
        "    color: darkblue;\n"
        "    }\n"
        "  scale trough {\n"
        "    color: darkblue;\n"
        "    }\n"
        "  #front_spin_button {\n"
        "    padding: 1px;\n"
        "    font-family: 'JetBrains Mono', Tahoma, Sans;\n"
        "    font-size: 13px;\n"
        "    font-weight: bold;\n"
        "    }\n"
        ;

char *css_dark =
        "/* deskHPSDR Industrial SDR Dark Theme - flat 2D */\n"
        "\n"
        "  * { font-family:'JetBrains Mono', Tahoma, Sans; }\n"
        "  combobox { font-size: 15px; }\n"
        "  button   { font-size: 15px; background-image: none; border-width: 2px; }\n"
        "  button:hover {\n"
        "    background-image: none;\n"
        "    box-shadow: none;\n"
        "  }\n"
        "  scrolledwindow viewport button:hover {\n"
        "    background-image: none;\n"
        "    border-width: 3px;\n"
        "  }\n"
        "  checkbutton label { font-size: 15px; }\n"
        "  spinbutton { font-size: 15px; }\n"
        "  radiobutton label  { font-size: 15px; }\n"
        "  scale { font-size: 15px; }\n"
        "  entry { font-size: 15px; }\n"
        "  textview.dxcluster-textview-linux {\n"
        "    font-family: 'JetBrains Mono', Tahoma, Sans;\n"
        "    font-size: 12pt;\n"
        "  }\n"
        "  entry.dxcluster-entry-linux {\n"
        "    font-family: 'JetBrains Mono', Tahoma, Sans;\n"
        "    font-size: 12pt;\n"
        "  }\n"
        "  textview.dxcluster-textview {\n"
        "    font-family: 'JetBrains Mono', Tahoma, Sans;\n"
        "    font-size: 14pt;\n"
        "  }\n"
        "  entry.dxcluster-entry {\n"
        "    font-family: 'JetBrains Mono', Tahoma, Sans;\n"
        "    font-size: 14pt;\n"
        "  }\n"
        "  notebook { font-size: 15px; }\n"
        "  #menu_separator {\n"
        "    background-color: #48515f;\n"
        "  }\n"
        "  tooltip, GtkWindow.tooltip {\n"
        "    text-shadow: none;\n"
        "    opacity: 1.0;\n"
        "    background-color: #202630;\n"
        "    background-image: none;\n"
        "    color: #e7edf4;\n"
        "  }\n"
        "  tooltip label, GtkWindow.tooltip label {\n"
        "    color: #e7edf4;\n"
        "    opacity: 1.0;\n"
        "    text-shadow: none;\n"
        "    font-family: 'JetBrains Mono', Tahoma, Sans;\n"
        "    font-size: 13px;\n"
        "  }\n"
        "  #boldlabel {\n"
        "    padding: 3px;\n"
        "    font-family: 'JetBrains Mono', Tahoma, Sans;\n"
        "    font-weight: bold;\n"
        "    font-size: 15px;\n"
        "  }\n"
        "  #boldlabel_vfo_sf {\n"
        "    padding: 3px;\n"
        "    border: 1px solid #4da3ff;\n"
        "    border-radius: 6px;\n"
        "    background-image: none;\n"
        "    font-family: 'JetBrains Mono', Tahoma, Sans;\n"
        "    font-weight: bold;\n"
        "    font-size: 15px;\n"
        "    color: #4da3ff;\n"
        "  }\n"
        "  #boldlabel_vfo_sf:hover {\n"
        "    background-color: #4da3ff;\n"
        "    background-image: none;\n"
        "  }\n"
        "  #boldlabel_red {\n"
        "    padding: 3px;\n"
        "    font-family: 'JetBrains Mono', Tahoma, Sans;\n"
        "    font-weight: bold;\n"
        "    font-size: 15px;\n"
        "    color: #ff5f6d;\n"
        "  }\n"
        "  #boldlabel_blue {\n"
        "    padding: 3px;\n"
        "    font-family: 'JetBrains Mono', Tahoma, Sans;\n"
        "    font-weight: bold;\n"
        "    font-size: 15px;\n"
        "    color: #4da3ff;\n"
        "  }\n"
        "  #boldlabel_border_blue {\n"
        "    padding: 3px;\n"
        "    border: 1px solid #4da3ff;\n"
        "    border-radius: 6px;\n"
        "    font-family: 'JetBrains Mono', Tahoma, Sans;\n"
        "    font-weight: bold;\n"
        "    font-size: 16px;\n"
        "    color: #4da3ff;\n"
        "  }\n"
        "  #boldlabel_border_black {\n"
        "    padding: 3px;\n"
        "    border: 2px solid #e7edf4;\n"
        "    border-radius: 6px;\n"
        "    font-family: 'JetBrains Mono', Tahoma, Sans;\n"
        "    font-weight: bold;\n"
        "    font-size: 16px;\n"
        "    color: #e7edf4;\n"
        "  }\n"
        "  #stdlabel {\n"
        "    padding: 3px;\n"
        "    font-family: 'JetBrains Mono', Tahoma, Sans;\n"
        "    font-weight: normal;\n"
        "    font-size: 15px;\n"
        "  }\n"
        "  #stdlabel_blue {\n"
        "    padding: 3px;\n"
        "    font-family: 'JetBrains Mono', Tahoma, Sans;\n"
        "    font-weight: normal;\n"
        "    font-size: 15px;\n"
        "    color: #4da3ff;\n"
        "  }\n"
        "  #smalllabel {\n"
        "    padding: 3px;\n"
        "    font-family: 'JetBrains Mono', Tahoma, Sans;\n"
        "    font-weight: normal;\n"
        "    font-size: 13px;\n"
        "  }\n"
        "  #smalllabel_bold {\n"
        "    font-family: 'JetBrains Mono', Tahoma, Sans;\n"
        "    font-weight: bold;\n"
        "    font-size: 13px;\n"
        "  }\n"
        "  #smalllabel_red {\n"
        "    font-family: 'JetBrains Mono', Tahoma, Sans;\n"
        "    font-weight: normal;\n"
        "    font-size: 13px;\n"
        "    color: #ff5f6d\n"
        "  }\n"
        "  #smalllabel_red_bold {\n"
        "    font-family: 'JetBrains Mono', Tahoma, Sans;\n"
        "    font-weight: bold;\n"
        "    font-size: 13px;\n"
        "    color: #ff5f6d\n"
        "  }\n"
        "  #smalllabel_blue_bold {\n"
        "    font-family: 'JetBrains Mono', Tahoma, Sans;\n"
        "    font-weight: bold;\n"
        "    font-size: 13px;\n"
        "    color: #4da3ff\n"
        "  }\n"
        "  #slider0   {\n"
        "    padding: 3px;\n"
        "    font-family: 'JetBrains Mono', Tahoma, Sans;\n"
        "    font-weight: bold;\n"
        "    font-size: 14px;\n"
        "  }\n"
        "  #slider1   {\n"
        "    padding: 3px;\n"
        "    font-family: 'JetBrains Mono', Tahoma, Sans;\n"
        "    font-weight: bold;\n"
        "    font-size: 16px;\n"
        "  }\n"
        "  #slider2   {\n"
        "    padding: 3px;\n"
        "    font-family: 'JetBrains Mono', Tahoma, Sans;\n"
        "    font-weight: normal;\n"
        "    font-size: 16px;\n"
        "  }\n"
        "  #slider2_blue {\n"
        "    padding: 3px;\n"
        "    font-family: 'JetBrains Mono', Tahoma, Sans;\n"
        "    font-weight: normal;\n"
        "    font-size: 16px;\n"
        "    color: #4da3ff;\n"
        "  }\n"
        "  #slider2_red {\n"
        "    padding: 3px;\n"
        "    font-family: 'JetBrains Mono', Tahoma, Sans;\n"
        "    font-weight: normal;\n"
        "    font-size: 16px;\n"
        "    color: #ff5f6d;\n"
        "  }\n"
        "  #label2_grey {\n"
        "    padding: 3px;\n"
        "    font-family: 'JetBrains Mono', Tahoma, Sans;\n"
        "    font-weight: normal;\n"
        "    font-size: 18px;\n"
        "    color: #9da8b7;\n"
        "  }\n"
        "  #slider3   {\n"
        "    padding: 3px;\n"
        "    font-family: 'JetBrains Mono', Tahoma, Sans;\n"
        "    font-weight: normal;\n"
        "    font-size: 22px;\n"
        "  }\n"
        "  #big_txt {\n"
        "    font-family: Tahoma, Sans;\n"
        "    font-size: 22px;\n"
        "    font-weight: bold;\n"
        "    }\n"
        "  #med_txt {\n"
        "    font-family: Tahoma, Sans;\n"
        "    font-size: 18px;\n"
        "    }\n"
        "  #med_bold_txt {\n"
        "    font-family: Tahoma, Sans;\n"
        "    font-size: 18px;\n"
        "    font-weight: bold;\n"
        "    }\n"
        "  #small_txt {\n"
        "    font-family: Tahoma, Sans;\n"
        "    font-weight: bold;\n"
        "    font-size: 12px;\n"
        "    }\n"
        "  #small_bold_txt {\n"
        "    font-family: Tahoma, Sans;\n"
        "    font-weight: bold;\n"
        "    font-size: 16px;\n"
        "    }\n"
        "  #small_bold_txt_blue {\n"
        "    font-family: Tahoma, Sans;\n"
        "    font-weight: bold;\n"
        "    font-size: 16px;\n"
        "    color: #4da3ff;\n"
        "    }\n"
        "  #discovery_btn {\n"
        "    padding: 3px;\n"
        "    border: 1px solid #4da3ff;\n"
        "    border-radius: 6px;\n"
        "    font-family: 'JetBrains Mono', Tahoma, Sans;\n"
        "    font-size: 18px;\n"
        "    font-weight: bold;\n"
        "    background-image: none;\n"
        "    color: #4da3ff;\n"
        "    }\n"
        "  #discovery_btn:hover {\n"
        "    background-color: #4da3ff;\n"
        "    background-image: none;\n"
        "    }\n"
        "  #close_button {\n"
        "    padding: 5px;\n"
        "    font-family: 'JetBrains Mono', Tahoma, Sans;\n"
        "    font-size: 15px;\n"
        "    font-weight: bold;\n"
        "    border: 1px solid rgb(50%, 50%, 50%);\n"
        "    background-image: none;\n"
        "    }\n"
        "  #close_button:hover {\n"
        "    background-color: #4da3ff;\n"
        "    background-image: none;\n"
        "    }\n"
        "  #small_button {\n"
        "    padding: 1px;\n"
        "    border: 1px solid #4da3ff;\n"
        "    border-radius: 6px;\n"
        "    font-family: 'JetBrains Mono', Tahoma, Sans;\n"
        "    font-size: 15px;\n"
        "    font-weight: bold;\n"
        "    color: #4da3ff;\n"
        "    background-image: none;\n"
        "    }\n"
        "  #medium_button {\n"
        "    padding: 1px;\n"
        "    border: 1px solid #4da3ff;\n"
        "    border-radius: 6px;\n"
        "    font-family: 'JetBrains Mono', Tahoma, Sans;\n"
        "    font-size: 20px;\n"
        "    font-weight: bold;\n"
        "    color: #4da3ff;\n"
        "    background-image: none;\n"
        "    }\n"
        "  #medium_button:hover {\n"
        "    background-color: #4da3ff;\n"
        "    background-image: none;\n"
        "    }\n"
        "  #large_button {\n"
        "    padding: 1px;\n"
        "    border: 1px solid #4da3ff;\n"
        "    border-radius: 6px;\n"
        "    font-family: 'JetBrains Mono', Tahoma, Sans;\n"
        "    font-size: 25px;\n"
        "    font-weight: bold;\n"
        "    color: #4da3ff;\n"
        "    background-image: none;\n"
        "    }\n"
        "  #small_button_with_border {\n"
        "    padding: 3px;\n"
        "    font-family: 'JetBrains Mono', Tahoma, Sans;\n"
        "    font-size: 15px;\n"
        "    border: 1px solid rgb(50%, 50%, 50%);\n"
        "    }\n"
        "  #small_toggle_button {\n"
        "    padding: 1px;\n"
        "    border: 1px solid #4da3ff;\n"
        "    font-family: 'JetBrains Mono', Tahoma, Sans;\n"
        "    font-size: 15px;\n"
        "    font-weight: bold;\n"
        "    background-image: none;\n"
        "    color: #4da3ff;\n"
        "    }\n"
        "  #small_toggle_button:checked {\n"
        "    padding: 1px;\n"
        "    border: 1px solid #4da3ff;\n"
        "    font-family: 'JetBrains Mono', Tahoma, Sans;\n"
        "    font-size: 15px;\n"
        "    font-weight: bold;\n"
        "    background-image: none;\n"
        "    background-color: #4da3ff;\n"
        "    color: rgb(0%, 0%, 0%);\n"
        "    }\n"
        "  #medium_toggle_button {\n"
        "    padding: 1px;\n"
        "    border: 1px solid #4da3ff;\n"
        "    border-radius: 6px;\n"
        "    font-family: 'JetBrains Mono', Tahoma, Sans;\n"
        "    font-size: 13px;\n"
        "    font-weight: bold;\n"
        "    background-image: none;\n"
        "    color: #4da3ff;\n"
        "    }\n"
        "  #medium_toggle_button.active {\n"
        "    padding: 1px;\n"
        "    border: 1px solid #4da3ff;\n"
        "    border-radius: 6px;\n"
        "    font-family: 'JetBrains Mono', Tahoma, Sans;\n"
        "    font-size: 13px;\n"
        "    font-weight: bold;\n"
        "    background-image: none;\n"
        "    background-color: #4da3ff;\n"
        "    color: #4da3ff;\n"
        "    }\n"
        "  #medium_toggle_button:checked {\n"
        "    padding: 1px;\n"
        "    border: 1px solid #4da3ff;\n"
        "    border-radius: 6px;\n"
        "    font-family: 'JetBrains Mono', Tahoma, Sans;\n"
        "    font-size: 13px;\n"
        "    font-weight: bold;\n"
        "    background-image: none;\n"
        "    background-color: #4da3ff;\n"
        "    color: #4da3ff;\n"
        "    }\n"
        "  #medium_toggle_button:active {\n"
        "    padding: 1px;\n"
        "    border: 1px solid #4da3ff;\n"
        "    border-radius: 6px;\n"
        "    font-family: 'JetBrains Mono', Tahoma, Sans;\n"
        "    font-size: 13px;\n"
        "    font-weight: bold;\n"
        "    background-image: none;\n"
        "    background-color: #4da3ff;\n"
        "    color: #4da3ff;\n"
        "    }\n"
        "  #front_toggle_button {\n"
        "    padding: 1px;\n"
        "    border: 1px solid #4da3ff;\n"
        "    border-radius: 6px;\n"
        "    font-family: 'JetBrains Mono', Tahoma, Sans;\n"
        "    font-size: 13px;\n"
        "    font-weight: bold;\n"
        "    background-image: none;\n"
        "    background-color: rgb(100%, 20%, 20%);\n"
        "    color: rgb(100%, 100%, 100%);\n"
        "    }\n"
        "  #front_toggle_button:checked {\n"
        "    padding: 1px;\n"
        "    border: 1px solid #4da3ff;\n"
        "    border-radius: 6px;\n"
        "    font-family: 'JetBrains Mono', Tahoma, Sans;\n"
        "    font-size: 13px;\n"
        "    font-weight: bold;\n"
        "    background-image: none;\n"
        "    background-color: #4da3ff;\n"
        "    color: rgb(0%, 0%, 0%);\n"
        "    }\n"
        "  #front_toggle_button:disabled {\n"
        "    padding: 1px;\n"
        "    border: 1px solid #48515f;\n"
        "    border-radius: 6px;\n"
        "    background-color: #2a2f38;\n"
        "    color: #737d8b;\n"
        "    }\n"
        "  #front_toggle_button:checked:disabled {\n"
        "    padding: 1px;\n"
        "    border: 1px solid #48515f;\n"
        "    border-radius: 6px;\n"
        "    background-color: #2a2f38;\n"
        "    color: #737d8b;\n"
        "    }\n"
        "  #popup_scale slider {\n"
        "    background: #4da3ff;\n"
        "    }\n"
        "  #popup_scale trough {\n"
        "    background: #1f4f7a;\n"
        "    }\n"
        "  #popup_scale value {\n"
        "    color: rgb(100%, 10%, 10%);\n"
        "    font-size: 15px;\n"
        "    }\n"
        "  checkbutton:checked > check {\n"
        "    border: 1px solid rgb(50%, 50%, 50%);\n"
        "    background-color: #4da3ff;\n"
        "    border-color: #4da3ff;\n"
        "    background-image: none;\n"
        "    }\n"
        "  radiobutton radio {\n"
        "    border: 1px solid rgb(50%, 50%, 50%);\n"
        "    }\n"
        "  headerbar {\n"
        "    min-height: 0px;\n"
        "    padding: 0px;\n"
        "    margin: 0px;\n"
        "    font-size: 15px;\n"
        "    font-family: Tahoma, Sans;\n"
        "    }\n"
        "  scale value {\n"
        "    color: #4da3ff;\n"
        "    font-weight: bold;\n"
        "    }\n"
        "  scale marks {\n"
        "    color: #4da3ff;\n"
        "    }\n"
        "  scale mark {\n"
        "    color: #4da3ff;\n"
        "    }\n"
        "  scale slider {\n"
        "    color: #4da3ff;\n"
        "    }\n"
        "  scale trough {\n"
        "    color: #4da3ff;\n"
        "    }\n"
        "  #front_spin_button {\n"
        "    padding: 1px;\n"
        "    font-family: 'JetBrains Mono', Tahoma, Sans;\n"
        "    font-size: 13px;\n"
        "    font-weight: bold;\n"
        "    }\n"
        "\n"
        "/* ---- Industrial SDR Dark Base ------------------------------------------------ */\n"
        "* {\n"
        "  color: #e7edf4;\n"
        "  background-image: none;\n"
        "  text-shadow: none;\n"
        "  box-shadow: none;\n"
        "  border-image: none;\n"
        "  -gtk-icon-shadow: none;\n"
        "}\n"
        "\n"
        "window,\n"
        "dialog,\n"
        ".background,\n"
        "GtkWindow,\n"
        "GtkDialog,\n"
        "box,\n"
        "grid,\n"
        "fixed,\n"
        "eventbox,\n"
        "viewport,\n"
        "scrolledwindow,\n"
        "notebook,\n"
        "notebook > stack,\n"
        "notebook > header,\n"
        "paned,\n"
        "frame,\n"
        "revealer,\n"
        "layout {\n"
        "  background-color: #111318;\n"
        "  color: #e7edf4;\n"
        "  background-image: none;\n"
        "  box-shadow: none;\n"
        "}\n"
        "\n"
        "/* Nur echtes Top-Level Fenster */\n"
        "window {\n"
        "  border: 1px solid #2f3540;\n"
        "}\n"
        "\n"
        "window:focus {\n"
        "  border-color: #4da3ff;\n"
        "}\n"
        "\n"
        "headerbar,\n"
        "menubar,\n"
        "menu,\n"
        "menuitem,\n"
        "popover,\n"
        "popup,\n"
        "combobox,\n"
        "combobox box,\n"
        "combobox window,\n"
        "combobox menu,\n"
        "combobox menuitem {\n"
        "  background-color: #1b1f27;\n"
        "  color: #e7edf4;\n"
        "  background-image: none;\n"
        "  box-shadow: none;\n"
        "}\n"
        "\n"
        "label {\n"
        "  background-color: transparent;\n"
        "  color: #e7edf4;\n"
        "}\n"
        "\n"
        "/* ---- Flat 2D Buttons -------------------------------------------------------- */\n"
        "button,\n"
        "#small_button,\n"
        "#medium_button,\n"
        "#large_button,\n"
        "#discovery_btn,\n"
        "#close_button,\n"
        "#small_button_with_border,\n"
        "#small_toggle_button,\n"
        "#medium_toggle_button,\n"
        "#front_toggle_button,\n"
        "spinbutton button,\n"
        "combobox button {\n"
        "  background-color: #202630;\n"
        "  background-image: none;\n"
        "  color: #e7edf4;\n"
        "  border: 2px solid #556070;\n"
        "  border-radius: 5px;\n"
        "  box-shadow: none;\n"
        "  text-shadow: none;\n"
        "  outline: none;\n"
        "}\n"
        "\n"
        "button:hover,\n"
        "#small_button:hover,\n"
        "#medium_button:hover,\n"
        "#large_button:hover,\n"
        "#discovery_btn:hover,\n"
        "#close_button:hover,\n"
        "#small_button_with_border:hover,\n"
        "#small_toggle_button:hover,\n"
        "#medium_toggle_button:hover,\n"
        "#front_toggle_button:hover,\n"
        "spinbutton button:hover,\n"
        "combobox button:hover {\n"
        "  background-color: #252c38;\n"
        "  background-image: none;\n"
        "  color: #e7edf4;\n"
        "  border-color: #6bb6ff;\n"
        "  box-shadow: none;\n"
        "}\n"
        "\n"
        "button:active,\n"
        "button:checked,\n"
        "button.active,\n"
        "#small_toggle_button:active,\n"
        "#small_toggle_button:checked,\n"
        "#small_toggle_button.active,\n"
        "#medium_toggle_button:active,\n"
        "#medium_toggle_button:checked,\n"
        "#medium_toggle_button.active,\n"
        "#front_toggle_button:active,\n"
        "#front_toggle_button:checked,\n"
        "#front_toggle_button.active,\n"
        "spinbutton button:active,\n"
        "combobox button:active {\n"
        "  background-color: #4da3ff;\n"
        "  background-image: none;\n"
        "  color: #07111d;\n"
        "  border-color: #4da3ff;\n"
        "  box-shadow: none;\n"
        "}\n"
        "\n"
        "button:disabled,\n"
        "#small_button:disabled,\n"
        "#medium_button:disabled,\n"
        "#large_button:disabled,\n"
        "#discovery_btn:disabled,\n"
        "#close_button:disabled,\n"
        "#small_toggle_button:disabled,\n"
        "#medium_toggle_button:disabled,\n"
        "#front_toggle_button:disabled,\n"
        "spinbutton button:disabled,\n"
        "combobox button:disabled {\n"
        "  background-color: #2a2f38;\n"
        "  background-image: none;\n"
        "  color: #737d8b;\n"
        "  border-color: #48515f;\n"
        "  box-shadow: none;\n"
        "}\n"
        "\n"
        "button:focus,\n"
        "spinbutton button:focus,\n"
        "combobox button:focus {\n"
        "  outline: none;\n"
        "  box-shadow: none;\n"
        "  border-color: #4da3ff;\n"
        "}\n"
        "\n"
        "/* ---- Entries / Spinbuttons / Textviews ------------------------------------- */\n"
        "entry,\n"
        "spinbutton,\n"
        "spinbutton entry,\n"
        "textview,\n"
        "textview text,\n"
        ".view {\n"
        "  background-color: #171a21;\n"
        "  background-image: none;\n"
        "  color: #e7edf4;\n"
        "  border: 1px solid #556070;\n"
        "  border-radius: 4px;\n"
        "  box-shadow: none;\n"
        "  text-shadow: none;\n"
        "}\n"
        "\n"
        "entry:focus,\n"
        "spinbutton:focus,\n"
        "spinbutton entry:focus,\n"
        "textview:focus,\n"
        ".view:focus {\n"
        "  border-color: #4da3ff;\n"
        "  box-shadow: none;\n"
        "}\n"
        "\n"
        "selection,\n"
        ".view:selected,\n"
        "textview text selection,\n"
        "entry selection {\n"
        "  background-color: #2f8cff;\n"
        "  color: #07111d;\n"
        "}\n"
        "\n"
        "/* ---- Labels by existing IDs ------------------------------------------------- */\n"
        "#boldlabel,\n"
        "#stdlabel,\n"
        "#smalllabel,\n"
        "#smalllabel_bold,\n"
        "#slider0,\n"
        "#slider1,\n"
        "#slider2,\n"
        "#slider3,\n"
        "#big_txt,\n"
        "#med_txt,\n"
        "#med_bold_txt,\n"
        "#small_txt,\n"
        "#small_bold_txt {\n"
        "  color: #e7edf4;\n"
        "  background-color: transparent;\n"
        "}\n"
        "\n"
        "#boldlabel_blue,\n"
        "#boldlabel_vfo_sf,\n"
        "#boldlabel_border_blue,\n"
        "#stdlabel_blue,\n"
        "#smalllabel_blue_bold,\n"
        "#slider2_blue,\n"
        "#small_bold_txt_blue {\n"
        "  color: #4da3ff;\n"
        "  background-color: transparent;\n"
        "}\n"
        "\n"
        "#boldlabel_red,\n"
        "#smalllabel_red,\n"
        "#smalllabel_red_bold,\n"
        "#slider2_red {\n"
        "  color: #ff5f6d;\n"
        "  background-color: transparent;\n"
        "}\n"
        "\n"
        "#label2_grey {\n"
        "  color: #9da8b7;\n"
        "  background-color: transparent;\n"
        "}\n"
        "\n"
        "#boldlabel_border_black,\n"
        "#boldlabel_border_blue,\n"
        "#boldlabel_vfo_sf {\n"
        "  border-color: #556070;\n"
        "  color: #e7edf4;\n"
        "  background-color: transparent;\n"
        "  box-shadow: none;\n"
        "}\n"
        "\n"
        "#boldlabel_vfo_sf:hover {\n"
        "  background-color: #252c38;\n"
        "  color: #4da3ff;\n"
        "}\n"
        "\n"
        "/* ---- Sliders / Scales ------------------------------------------------------- */\n"
        "scale,\n"
        "scale trough,\n"
        "scale slider,\n"
        "scale highlight,\n"
        "scale value,\n"
        "scale marks,\n"
        "scale mark {\n"
        "  background-image: none;\n"
        "  box-shadow: none;\n"
        "  text-shadow: none;\n"
        "}\n"
        "\n"
        "scale value,\n"
        "scale marks,\n"
        "scale mark {\n"
        "  color: #4da3ff;\n"
        "  font-weight: bold;\n"
        "}\n"
        "\n"
        "scale trough {\n"
        "  background-color: #202630;\n"
        "  border: 1px solid #556070;\n"
        "  min-height: 6px;\n"
        "  border-radius: 3px;\n"
        "}\n"
        "\n"
        "scale highlight {\n"
        "  background-color: #4da3ff;\n"
        "  border-radius: 3px;\n"
        "}\n"
        "\n"
        "scale slider,\n"
        "#popup_scale slider {\n"
        "  background-color: #4da3ff;\n"
        "  border: 1px solid #6bb6ff;\n"
        "  border-radius: 4px;\n"
        "  min-width: 14px;\n"
        "  min-height: 14px;\n"
        "}\n"
        "\n"
        "#popup_scale trough {\n"
        "  background-color: #202630;\n"
        "}\n"
        "\n"
        "#popup_scale value {\n"
        "  color: #ff5f6d;\n"
        "}\n"
        "\n"
        "/* ---- Check / Radio ---------------------------------------------------------- */\n"
        "checkbutton,\n"
        "radiobutton,\n"
        "checkbutton label,\n"
        "radiobutton label {\n"
        "  color: #e7edf4;\n"
        "  background-color: transparent;\n"
        "}\n"
        "\n"
        "checkbutton check,\n"
        "radiobutton radio {\n"
        "  background-color: #171a21;\n"
        "  border: 2px solid #556070;\n"
        "  box-shadow: none;\n"
        "  background-image: none;\n"
        "}\n"
        "\n"
        "checkbutton:checked > check,\n"
        "radiobutton:checked > radio {\n"
        "  background-color: #4da3ff;\n"
        "  border-color: #4da3ff;\n"
        "  color: #07111d;\n"
        "}\n"
        "\n"
        "/* ---- Tooltips --------------------------------------------------------------- */\n"
        "tooltip,\n"
        "GtkWindow.tooltip {\n"
        "  background-color: #202630;\n"
        "  color: #e7edf4;\n"
        "  border: 1px solid #748196;\n"
        "  opacity: 1.0;\n"
        "  text-shadow: none;\n"
        "  box-shadow: none;\n"
        "}\n"
        "\n"
        "tooltip label,\n"
        "GtkWindow.tooltip label {\n"
        "  color: #e7edf4;\n"
        "  opacity: 1.0;\n"
        "  text-shadow: none;\n"
        "  background-color: transparent;\n"
        "}\n"
        "\n"
        "*:disabled,\n"
        "*:disabled {\n"
        "  color: #737d8b;\n"
        "  text-shadow: none;\n"
        "  box-shadow: none;\n"
        "}\n"
        "\n"
        "textview.dxcluster-textview-linux,\n"
        "entry.dxcluster-entry-linux,\n"
        "textview.dxcluster-textview,\n"
        "entry.dxcluster-entry {\n"
        "  background-color: #171a21;\n"
        "  color: #e7edf4;\n"
        "  border-color: #556070;\n"
        "}\n"
        "\n"
        "/* ---- Hard UI status colors -------------------------------------------------- */\n"
        "#front_toggle_button {\n"
        "  background-color: #ff5f6d;\n"
        "  color: #07111d;\n"
        "  border-color: #ff5f6d;\n"
        "}\n"
        "\n"
        "#front_toggle_button:checked {\n"
        "  background-color: #4da3ff;\n"
        "  color: #07111d;\n"
        "  border-color: #4da3ff;\n"
        "}\n"
        "\n"
        "#front_toggle_button:disabled,\n"
        "#front_toggle_button:checked:disabled {\n"
        "  background-color: #2a2f38;\n"
        "  color: #737d8b;\n"
        "  border-color: #48515f;\n"
        "}\n"
        "\n"
        "/* ---- Safety catch-all against light dialog content ------------------------- */\n"
        "dialog *:not(button):not(entry):not(textview):not(scale):not(check):not(radio):not(slider),\n"
        "window *:not(button):not(entry):not(textview):not(scale):not(check):not(radio):not(slider) {\n"
        "  background-image: none;\n"
        "  box-shadow: none;\n"
        "}\n"
        ;

void StartConfigSave(void) {
  clearProperties();
  const char *filename = "startup_config.props";
  SetPropI0("css_dark_theme", css_dark_theme);
  SetPropI0("iaru_region", iaru_region);
  SetPropI0("display_debug", display_debug);
  SetPropI0("display_sysinfo", display_sysinfo);
  SetPropI0("log_debug", log_debug);
  SetPropI0("ui_debug", ui_debug);
  SetPropI0("freq_bgcolor_alter", freq_bgcolor_alter);
  SetPropI0("sertune_ptt_hold_ms", sertune_ptt_hold_ms);
  SetPropI0("sertune_invert", sertune_invert);
  SetPropI0("p2_angelia_ddc0_map", p2_angelia_ddc0_map);
  SetPropI0("brick_ddc0_fix", brick_ddc0_fix);
  SetPropS0("radio_host", ipaddr_radio);
  SetPropI0("radio_port", radio_port);
  SetPropI0("enable_protocol_1", enable_protocol_1);
  SetPropI0("enable_protocol_2", enable_protocol_2);
  SetPropI0("enable_stemlab", enable_stemlab);
  SetPropI0("enable_usbozy", enable_usbozy);
  SetPropI0("enable_saturn_xdma", enable_saturn_xdma);
  SetPropI0("autostart", autostart);
  for (int i = 0; i < P2_MAX_DDCS; i++) {
    char name[32];
    snprintf(name, sizeof(name), "p2_ddc%d_adc", i);
    SetPropI0(name, p2_ddc_adc_map[i]);
  }
  saveProperties(filename);
}

void StartConfigLoad(void) {
  const char *filename = "startup_config.props";
  if (!filename || access(filename, F_OK) != 0) {
    return;
  }
  loadProperties(filename);
  GetPropI0("css_dark_theme", css_dark_theme);
  GetPropI0("iaru_region", iaru_region);
  GetPropI0("display_debug", display_debug);
  GetPropI0("display_sysinfo", display_sysinfo);
  GetPropI0("log_debug", log_debug);
  GetPropI0("ui_debug", ui_debug);
  GetPropI0("qrg_bg_color_alter", freq_bgcolor_alter);
  GetPropI0("freq_bgcolor_alter", freq_bgcolor_alter);
  GetPropI0("sertune_ptt_hold_ms", sertune_ptt_hold_ms);
  GetPropI0("sertune_invert", sertune_invert);
  GetPropI0("p2_angelia_ddc0_map", p2_angelia_ddc0_map);
  GetPropI0("brick_ddc0_fix", brick_ddc0_fix);
  const char *radio_host = getProperty("radio_host");
  if (radio_host) {
    g_strlcpy(ipaddr_radio, radio_host, IPADDR_LEN);
  }
  GetPropI0("radio_port", radio_port);
  GetPropI0("enable_protocol_1", enable_protocol_1);
  GetPropI0("enable_protocol_2", enable_protocol_2);
  GetPropI0("enable_stemlab", enable_stemlab);
  GetPropI0("enable_usbozy", enable_usbozy);
  GetPropI0("enable_saturn_xdma", enable_saturn_xdma);
  GetPropI0("autostart", autostart);
  if (radio_port < 1 || radio_port > 65535) {
    radio_port = 1024;
  }
  p2_angelia_ddc0_map = p2_angelia_ddc0_map ? 1 : 0;
  for (int i = 0; i < P2_MAX_DDCS; i++) {
    char name[32];
    snprintf(name, sizeof(name), "p2_ddc%d_adc", i);
    GetPropI0(name, p2_ddc_adc_map[i]);
    p2_ddc_adc_map[i] = p2_ddc_adc_map[i] ? 1 : 0;
  }
  if (iaru_region < 1 || iaru_region > 3) {
    iaru_region = 2;
  }
  if (display_debug < 0 || display_debug > 1) {
    display_debug = 0;
  }
  if (display_sysinfo < 0 || display_sysinfo > 1) {
    display_sysinfo = 0;
  }
  if (log_debug < 0 || log_debug > 1) {
    log_debug = 0;
  }
  if (freq_bgcolor_alter < 0 || freq_bgcolor_alter > 1) {
    freq_bgcolor_alter = 0;
  }
  if (ui_debug < 0 || ui_debug > 1) {
    ui_debug = 0;
  }
  if (brick_ddc0_fix < 0 || brick_ddc0_fix > 1) {
    brick_ddc0_fix = 0;
  }
  if (sertune_ptt_hold_ms < 0) {
    sertune_ptt_hold_ms = 500;
  }
  if (sertune_invert < 0 || sertune_invert > 1) {
    sertune_invert = 0;
  }
  clearProperties();
}

void load_css(void) {
  GdkDisplay *display = gdk_display_get_default();
  GdkScreen *screen = gdk_display_get_default_screen(display);
  GError *error = NULL;
  /* alten Provider entfernen (wichtig für Theme-Switch) */
  static GtkCssProvider *current_provider = NULL;
  if (current_provider != NULL) {
    gtk_style_context_remove_provider_for_screen(screen,
        GTK_STYLE_PROVIDER(current_provider));
    g_object_unref(current_provider);
    current_provider = NULL;
  }
  GtkCssProvider *provider = gtk_css_provider_new();
  // 1. Laden aus Datei
  if (css_dark_theme) {
    css_filename = "deskhpsdr-dark.css";
  } else {
    css_filename = "deskhpsdr.css";
  }
  gtk_css_provider_load_from_path(provider, css_filename, &error);
  if (!error) {
    gtk_style_context_add_provider_for_screen(screen,
        GTK_STYLE_PROVIDER(provider),
        GTK_STYLE_PROVIDER_PRIORITY_APPLICATION);
    t_print("%s: CSS data loaded from file %s\n", __func__, css_filename);
  } else {
    t_print("%s: failed to load CSS data from file %s: %s\n",
            __func__, css_filename, extract_short_msg(error->message));
    g_clear_error(&error);
    // 2. Laden aus Hardcoded-String
    if (css_dark_theme) {
      gtk_css_provider_load_from_data(provider, css_dark, -1, &error);
    } else {
      gtk_css_provider_load_from_data(provider, css, -1, &error);
    }
    if (!error) {
      gtk_style_context_add_provider_for_screen(screen,
          GTK_STYLE_PROVIDER(provider),
          GTK_STYLE_PROVIDER_PRIORITY_APPLICATION);
      t_print("%s: hard-coded CSS data successfully loaded\n", __func__);
    } else {
      t_print("%s: failed to load hard-coded CSS data: %s\n",
              __func__, extract_short_msg(error->message));
      g_clear_error(&error);
      g_object_unref(provider);
      provider = NULL;
    }
  }
  /* Provider merken für nächsten Reload */
  if (provider != NULL) {
    current_provider = provider;
  }
  StartConfigSave();
}

void save_css(GtkWidget *widget, gpointer data) {
  const char *file_name = css_dark_theme ? "deskhpsdr-dark.css" : "deskhpsdr.css";
  FILE *file = fopen(file_name, "w");
  if (file == NULL) {
    t_print("%s: Error opening %s for writing\n", __func__, file_name);
    return;
  }
  const char *src = css_dark_theme ? css_dark : css;
  if (fputs(src, file) == EOF) {
    t_print("%s: Error writing to %s\n", __func__, file_name);
  } else {
    t_print("%s: Hard-coded CSS successfully written to %s\n", __func__, file_name);
  }
  fclose(file);
  load_css();   /* Theme neu laden */
  screen_menu_cleanup();
  screen_menu(top_window);
}

void remove_css(GtkWidget *widget, gpointer data) {
  const char *file_name = css_dark_theme ? "deskhpsdr-dark.css" : "deskhpsdr.css";
  errno = 0;
  int rc = remove(file_name);
  if (rc == 0) {
    t_print("%s: %s successfully deleted\n", __func__, file_name);
  } else {
    if (errno == ENOENT) {
      t_print("%s: %s not found (nothing to delete)\n", __func__, file_name);
    } else {
      t_print("%s: Error deleting %s: %s\n", __func__, file_name, strerror(errno));
    }
  }
  load_css();
  screen_menu_cleanup();
  screen_menu(top_window);
}
